#--------------------------------------#
#          Kits Configuration          #
#--------------------------------------#
#                                      #
# The amount of bars in kit creation   #
# chere are in the kits. T             #
#                                      #
# Delays can be set up when spawning   #
# kits. Delays are managed in seconds. #
#                                      #
#--------------------------------------#
#                                      #
# By the way, all kits are stored in   #
# kits.yml - you shouldnt edit this    #
# file unless you know what you're     #
# doing, and I recommend you create    #
# and edit kits in-game as its easier. #
#                                      #
#--------------------------------------#

options:
  bars: 1
  delay: 0
  overwrite: false